<?php
/**
 * config.php — GeoNarrative Application Configuration
 *
 * IMPORTANT: After first deployment, run setup.php ONCE to generate
 * your password hash, paste it below, then DELETE setup.php from the server.
 *
 * Never store a plain-text password here — always use the hash.
 */

// ── Editor password (bcrypt hash) ─────────────────────────────────
// Default hash below is for the password: geonarrative
// Replace with your own hash generated by setup.php
define('EDITOR_PASSWORD_HASH',
    '$2y$12$lU33LwZaQohdIhf0k/w8ZeW7442JDsOXV18mJiOz4Vt2GgNAS2PlS'
);

// ── Session settings ───────────────────────────────────────────────
define('SESSION_NAME',    'geonarrative_session');
define('SESSION_TIMEOUT', 7200);   // seconds — 2 hours idle timeout

// ── Application paths ──────────────────────────────────────────────
define('STORIES_DIR',  __DIR__ . '/stories/');
define('STORIES_URL',  'stories/');

// ── Application name ───────────────────────────────────────────────
define('APP_NAME', 'GeoNarrative');
